import React, { useState, useMemo } from 'react';
import { ShoppingItem } from '../hooks/useShoppingList';
import './ShoppingList.css';

const DEFAULT_VISIBLE = 20;

interface Props {
  items: ShoppingItem[];
  onClose: () => void;
}

function buildExportText(items: ShoppingItem[], checkedIds: Set<string>, hiddenIds: Set<string>): string {
  const visible = items.filter(i => !hiddenIds.has(i.ingredientId) && !checkedIds.has(i.ingredientId));
  const inCart  = items.filter(i => checkedIds.has(i.ingredientId) && !hiddenIds.has(i.ingredientId));

  if (visible.length === 0 && inCart.length === 0) {
    return 'My thepour Shopping List 🍸\n\nAll done — nothing left to buy!\n\nGenerated by thepour.ai';
  }

  const lines: string[] = ['My thepour Shopping List 🍸', ''];

  const topPicks = visible.filter(i => i.unlocksCount > 0).slice(0, 5);
  const topPickIds = new Set(topPicks.map(i => i.ingredientId));
  const rest = visible.filter(i => !topPickIds.has(i.ingredientId));

  if (topPicks.length > 0) {
    lines.push('TOP PICKS (most recipes unlocked):');
    topPicks.forEach(i => {
      lines.push(`- ${i.name} — unlocks ${i.unlocksCount} recipe${i.unlocksCount !== 1 ? 's' : ''}`);
    });
    lines.push('');
  }

  const sections: [string, ShoppingItem['category']][] = [
    ['SPIRITS', 'spirit'],
    ['LIQUEURS', 'liqueur'],
    ['MIXERS', 'mixer'],
    ['PANTRY', 'pantry'],
    ['OTHER', 'other'],
  ];

  sections.forEach(([label, cat]) => {
    const sectionItems = rest.filter(i => i.category === cat);
    if (sectionItems.length === 0) return;
    lines.push(`${label}:`);
    sectionItems.forEach(i => {
      const note = i.unlocksCount > 0 ? ` (unlocks ${i.unlocksCount})` : '';
      lines.push(`- ${i.name}${note}`);
    });
    lines.push('');
  });

  if (inCart.length > 0) {
    lines.push('IN MY CART:');
    inCart.forEach(i => lines.push(`- ${i.name} ✓`));
    lines.push('');
  }

  lines.push('Generated by thepour.ai');
  return lines.join('\n');
}

export function ShoppingList({ items, onClose }: Props) {
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [checkedIds,  setCheckedIds]  = useState<Set<string>>(new Set());
  // hiddenIds covers: items deleted in edit mode + items cleared from cart
  const [hiddenIds,   setHiddenIds]   = useState<Set<string>>(new Set());
  const [showAll,     setShowAll]     = useState(false);
  const [editMode,    setEditMode]    = useState(false);
  const [copyToast,   setCopyToast]   = useState(false);

  // Visible pool — exclude hidden items
  const allVisible = useMemo(
    () => items.filter(i => !hiddenIds.has(i.ingredientId)),
    [items, hiddenIds]
  );

  const mainItems = useMemo(
    () => allVisible.filter(i => !checkedIds.has(i.ingredientId)),
    [allVisible, checkedIds]
  );

  const cartItems = useMemo(
    () => allVisible.filter(i => checkedIds.has(i.ingredientId)),
    [allVisible, checkedIds]
  );

  const displayedMain = showAll ? mainItems : mainItems.slice(0, DEFAULT_VISIBLE);
  const hiddenCount   = mainItems.length - DEFAULT_VISIBLE;

  function toggleExpand(id: string) {
    setExpandedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function toggleCheck(id: string) {
    setCheckedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function hideItem(id: string) {
    setHiddenIds(prev => { const n = new Set(Array.from(prev)); n.add(id); return n; });
    setCheckedIds(prev => { const n = new Set(Array.from(prev)); n.delete(id); return n; });
    setExpandedIds(prev => { const n = new Set(Array.from(prev)); n.delete(id); return n; });
  }

  function clearCart() {
    setHiddenIds(prev => new Set(Array.from(prev).concat(Array.from(checkedIds))));
    setCheckedIds(new Set());
  }

  function resetList() {
    setHiddenIds(new Set());
    setEditMode(false);
  }

  function handleCopy() {
    const text = buildExportText(items, checkedIds, hiddenIds);
    navigator.clipboard.writeText(text).then(() => {
      setCopyToast(true);
      setTimeout(() => setCopyToast(false), 2000);
    });
  }

  function handleEmail() {
    const body = encodeURIComponent(buildExportText(items, checkedIds, hiddenIds));
    window.location.href = `mailto:?subject=My%20thepour%20Shopping%20List&body=${body}`;
  }

  function handleSMS() {
    const body = encodeURIComponent(buildExportText(items, checkedIds, hiddenIds));
    window.location.href = `sms:?body=${body}`;
  }

  const hiddenItemCount = hiddenIds.size;

  function renderItem(item: ShoppingItem, isCart: boolean) {
    const isChecked  = checkedIds.has(item.ingredientId);
    const isExpanded = expandedIds.has(item.ingredientId);
    const hasRecipes = item.recipes.length > 0;

    return (
      <div key={item.ingredientId} className={`sl-item${isCart ? ' sl-item--cart' : ''}${editMode ? ' sl-item--edit' : ''}`}>
        <div className="sl-item-row">
          {!editMode && (
            <button
              className={`sl-checkbox${isChecked ? ' sl-checkbox--checked' : ''}`}
              onClick={() => toggleCheck(item.ingredientId)}
              aria-label={isChecked ? 'Remove from cart' : 'Add to cart'}
            >
              {isChecked && '✓'}
            </button>
          )}

          <div
            className="sl-item-body"
            onClick={() => !editMode && hasRecipes && toggleExpand(item.ingredientId)}
            style={{ cursor: !editMode && hasRecipes ? 'pointer' : 'default' }}
          >
            <span className="sl-item-name">{item.name}</span>
            <div className="sl-item-meta">
              <span className={`sl-pill sl-pill--${item.category}`}>{item.category}</span>
              {item.unlocksCount > 0 && (
                <span className="sl-badge">
                  unlocks {item.unlocksCount} {item.unlocksCount === 1 ? 'recipe' : 'recipes'}
                </span>
              )}
            </div>
          </div>

          {editMode ? (
            <button
              className="sl-delete-btn"
              onClick={() => hideItem(item.ingredientId)}
              aria-label="Remove from list"
            >
              ✕
            </button>
          ) : hasRecipes ? (
            <button
              className={`sl-expand-btn${isExpanded ? ' sl-expand-btn--open' : ''}`}
              onClick={() => toggleExpand(item.ingredientId)}
              aria-label={isExpanded ? 'Collapse' : 'Expand'}
            >
              ›
            </button>
          ) : null}
        </div>

        {!editMode && isExpanded && hasRecipes && (
          <div className="sl-recipes">
            {item.recipes.map(name => (
              <span key={name} className="sl-recipe-chip">{name}</span>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="sl-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="sl-panel">

        {/* Header */}
        <div className="sl-header">
          <div className="sl-header-text">
            <h2 className="sl-title">What to buy next</h2>
            <p className="sl-subtitle">Based on your current bar</p>
          </div>
          <div className="sl-header-actions">
            {editMode ? (
              <>
                {hiddenItemCount > 0 && (
                  <button className="sl-reset-btn" onClick={resetList}>
                    Reset list
                  </button>
                )}
                <button className="sl-edit-btn sl-edit-btn--active" onClick={() => setEditMode(false)}>
                  Done
                </button>
              </>
            ) : (
              <button
                className="sl-edit-btn"
                onClick={() => setEditMode(true)}
                aria-label="Edit list"
                title="Edit list"
              >
                ✏️
              </button>
            )}
            <button className="sl-close-btn" onClick={onClose} aria-label="Close">✕</button>
          </div>
        </div>

        {/* List */}
        <div className="sl-list">
          {mainItems.length === 0 && cartItems.length === 0 && (
            <p className="sl-empty">Your bar is fully stocked — nothing to buy!</p>
          )}

          {/* Main items */}
          {displayedMain.map(item => renderItem(item, false))}

          {/* Show all / Show less toggle */}
          {!showAll && hiddenCount > 0 && (
            <button className="sl-show-more" onClick={() => setShowAll(true)}>
              Show {hiddenCount} more item{hiddenCount !== 1 ? 's' : ''}
            </button>
          )}
          {showAll && mainItems.length > DEFAULT_VISIBLE && (
            <button className="sl-show-more" onClick={() => setShowAll(false)}>
              Show less
            </button>
          )}

          {/* In my cart section */}
          {cartItems.length > 0 && (
            <>
              <div className="sl-cart-header">
                <span className="sl-cart-label">In my cart</span>
                <button className="sl-clear-cart-btn" onClick={clearCart}>
                  Clear cart
                </button>
              </div>
              {cartItems.map(item => renderItem(item, true))}
            </>
          )}
        </div>

        {/* Export bar */}
        <div className="sl-export-bar">
          <button className="sl-export-btn" onClick={handleCopy}>
            {copyToast ? '✓ Copied!' : '📋 Copy'}
          </button>
          <button className="sl-export-btn" onClick={handleEmail}>✉️ Email</button>
          <button className="sl-export-btn" onClick={handleSMS}>💬 Text</button>
        </div>
      </div>
    </div>
  );
}
