import React, { useState, useMemo } from 'react';
import { ShoppingItem } from '../hooks/useShoppingList';
import './ShoppingList.css';

interface Props {
  items: ShoppingItem[];
  onClose: () => void;
}

function buildExportText(items: ShoppingItem[], checkedIds: Set<string>): string {
  const unchecked = items.filter(i => !checkedIds.has(i.ingredientId));
  if (unchecked.length === 0) {
    return 'My thepour Shopping List 🍸\n\nAll done — nothing left to buy!\n\nGenerated by thepour.ai';
  }

  const lines: string[] = ['My thepour Shopping List 🍸', ''];

  const topPicks = unchecked.filter(i => i.unlocksCount > 0).slice(0, 5);
  const topPickIds = new Set(topPicks.map(i => i.ingredientId));
  const rest = unchecked.filter(i => !topPickIds.has(i.ingredientId));

  if (topPicks.length > 0) {
    lines.push('TOP PICKS (most recipes unlocked):');
    topPicks.forEach(i => {
      lines.push(`- ${i.name} — unlocks ${i.unlocksCount} recipe${i.unlocksCount !== 1 ? 's' : ''}`);
    });
    lines.push('');
  }

  const sections: [string, ShoppingItem['category']][] = [
    ['SPIRITS', 'spirit'],
    ['LIQUEURS', 'liqueur'],
    ['MIXERS', 'mixer'],
    ['PANTRY', 'pantry'],
    ['OTHER', 'other'],
  ];

  sections.forEach(([label, cat]) => {
    const sectionItems = rest.filter(i => i.category === cat);
    if (sectionItems.length === 0) return;
    lines.push(`${label}:`);
    sectionItems.forEach(i => {
      const note = i.unlocksCount > 0 ? ` (unlocks ${i.unlocksCount})` : '';
      lines.push(`- ${i.name}${note}`);
    });
    lines.push('');
  });

  lines.push('Generated by thepour.ai');
  return lines.join('\n');
}

export function ShoppingList({ items, onClose }: Props) {
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [copyToast, setCopyToast] = useState(false);

  const sortedItems = useMemo(() => {
    const unchecked = items.filter(i => !checkedIds.has(i.ingredientId));
    const checked = items.filter(i => checkedIds.has(i.ingredientId));
    return [...unchecked, ...checked];
  }, [items, checkedIds]);

  function toggleExpand(id: string) {
    setExpandedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function toggleCheck(id: string) {
    setCheckedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function handleCopy() {
    const text = buildExportText(items, checkedIds);
    navigator.clipboard.writeText(text).then(() => {
      setCopyToast(true);
      setTimeout(() => setCopyToast(false), 2000);
    });
  }

  function handleEmail() {
    const body = encodeURIComponent(buildExportText(items, checkedIds));
    window.location.href = `mailto:?subject=My%20thepour%20Shopping%20List&body=${body}`;
  }

  function handleSMS() {
    const body = encodeURIComponent(buildExportText(items, checkedIds));
    window.location.href = `sms:?body=${body}`;
  }

  const hasChecked = checkedIds.size > 0;

  return (
    <div className="sl-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="sl-panel">

        <div className="sl-header">
          <div className="sl-header-text">
            <h2 className="sl-title">What to buy next</h2>
            <p className="sl-subtitle">Based on your current bar</p>
          </div>
          <div className="sl-header-actions">
            {hasChecked && (
              <button className="sl-clear-btn" onClick={() => setCheckedIds(new Set())}>
                Clear checked
              </button>
            )}
            <button className="sl-close-btn" onClick={onClose} aria-label="Close">✕</button>
          </div>
        </div>

        <div className="sl-list">
          {sortedItems.length === 0 && (
            <p className="sl-empty">Your bar is fully stocked — nothing to buy!</p>
          )}

          {sortedItems.map(item => {
            const isChecked = checkedIds.has(item.ingredientId);
            const isExpanded = expandedIds.has(item.ingredientId);
            const hasRecipes = item.recipes.length > 0;

            return (
              <div key={item.ingredientId} className={`sl-item${isChecked ? ' sl-item--checked' : ''}`}>
                <div className="sl-item-row">
                  <button
                    className={`sl-checkbox${isChecked ? ' sl-checkbox--checked' : ''}`}
                    onClick={() => toggleCheck(item.ingredientId)}
                    aria-label={isChecked ? 'Uncheck item' : 'Check item'}
                  >
                    {isChecked && '✓'}
                  </button>

                  <div
                    className="sl-item-body"
                    onClick={() => hasRecipes && toggleExpand(item.ingredientId)}
                    style={{ cursor: hasRecipes ? 'pointer' : 'default' }}
                  >
                    <span className="sl-item-name">{item.name}</span>
                    <div className="sl-item-meta">
                      <span className={`sl-pill sl-pill--${item.category}`}>{item.category}</span>
                      {item.unlocksCount > 0 && (
                        <span className="sl-badge">
                          unlocks {item.unlocksCount} {item.unlocksCount === 1 ? 'recipe' : 'recipes'}
                        </span>
                      )}
                    </div>
                  </div>

                  {hasRecipes && (
                    <button
                      className={`sl-expand-btn${isExpanded ? ' sl-expand-btn--open' : ''}`}
                      onClick={() => toggleExpand(item.ingredientId)}
                      aria-label={isExpanded ? 'Collapse' : 'Expand'}
                    >
                      ›
                    </button>
                  )}
                </div>

                {isExpanded && hasRecipes && (
                  <div className="sl-recipes">
                    {item.recipes.map(name => (
                      <span key={name} className="sl-recipe-chip">{name}</span>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <div className="sl-export-bar">
          <button className="sl-export-btn" onClick={handleCopy}>
            {copyToast ? '✓ Copied!' : '📋 Copy'}
          </button>
          <button className="sl-export-btn" onClick={handleEmail}>✉️ Email</button>
          <button className="sl-export-btn" onClick={handleSMS}>💬 Text</button>
        </div>
      </div>
    </div>
  );
}
