import React, { useState, useMemo } from 'react';
import { ShoppingItem } from '../hooks/useShoppingList';
import './ShoppingList.css';

const DEFAULT_VISIBLE = 20;

interface Props {
  items: ShoppingItem[];
  onClose: () => void;
  initialCheckedIds?: Set<string>;
  note?: string;
}

function buildExportText(selected: ShoppingItem[]): string {
  if (selected.length === 0) {
    return 'My thepour Shopping List 🍸\n\nGenerated by thepour.ai';
  }

  const lines: string[] = ['My thepour Shopping List 🍸', ''];

  const sections: [string, ShoppingItem['category']][] = [
    ['SPIRITS', 'spirit'],
    ['LIQUEURS', 'liqueur'],
    ['MIXERS', 'mixer'],
    ['PANTRY', 'pantry'],
    ['OTHER', 'other'],
  ];

  sections.forEach(([label, cat]) => {
    const sectionItems = selected.filter(i => i.category === cat);
    if (sectionItems.length === 0) return;
    lines.push(`${label}:`);
    sectionItems.forEach(i => {
      const note = i.unlocksCount > 0 ? ` — unlocks ${i.unlocksCount} recipe${i.unlocksCount !== 1 ? 's' : ''}` : '';
      lines.push(`- ${i.name}${note}`);
    });
    lines.push('');
  });

  lines.push('Generated by thepour.ai');
  return lines.join('\n');
}

export function ShoppingList({ items, onClose, initialCheckedIds, note }: Props) {
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [checkedIds,  setCheckedIds]  = useState<Set<string>>(
    () => initialCheckedIds ? new Set(Array.from(initialCheckedIds)) : new Set()
  );
  const [hiddenIds,   setHiddenIds]   = useState<Set<string>>(new Set());
  const [showAll,     setShowAll]     = useState(false);
  const [editMode,    setEditMode]    = useState(false);
  const [copyToast,   setCopyToast]   = useState(false);

  const visibleItems = useMemo(
    () => items.filter(i => !hiddenIds.has(i.ingredientId)),
    [items, hiddenIds]
  );

  const displayedItems = showAll ? visibleItems : visibleItems.slice(0, DEFAULT_VISIBLE);
  const remainingCount = visibleItems.length - DEFAULT_VISIBLE;

  const selectedItems = useMemo(
    () => items.filter(i => checkedIds.has(i.ingredientId) && !hiddenIds.has(i.ingredientId)),
    [items, checkedIds, hiddenIds]
  );

  function toggleExpand(id: string) {
    setExpandedIds(prev => {
      const n = new Set(Array.from(prev));
      n.has(id) ? n.delete(id) : n.add(id);
      return n;
    });
  }

  function toggleCheck(id: string) {
    setCheckedIds(prev => {
      const n = new Set(Array.from(prev));
      n.has(id) ? n.delete(id) : n.add(id);
      return n;
    });
  }

  function selectTop10() {
    const top10 = visibleItems.slice(0, 10).map(i => i.ingredientId);
    setCheckedIds(new Set(top10));
  }

  function hideItem(id: string) {
    setHiddenIds(prev => { const n = new Set(Array.from(prev)); n.add(id); return n; });
    setCheckedIds(prev => { const n = new Set(Array.from(prev)); n.delete(id); return n; });
    setExpandedIds(prev => { const n = new Set(Array.from(prev)); n.delete(id); return n; });
  }

  function resetList() {
    setHiddenIds(new Set());
    setEditMode(false);
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildExportText(selectedItems)).then(() => {
      setCopyToast(true);
      setTimeout(() => setCopyToast(false), 2000);
    });
  }

  function handleEmail() {
    const body = encodeURIComponent(buildExportText(selectedItems));
    window.location.href = `mailto:?subject=My%20thepour%20Shopping%20List&body=${body}`;
  }

  function handleSMS() {
    const body = encodeURIComponent(buildExportText(selectedItems));
    window.location.href = `sms:?body=${body}`;
  }

  const hasSelection = selectedItems.length > 0;

  return (
    <div className="sl-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="sl-panel">

        {/* ── Header ── */}
        <div className="sl-header">
          <div className="sl-header-text">
            <h2 className="sl-title">What to buy next</h2>
            <p className="sl-subtitle">Based on your current bar</p>
            {note && <p className="sl-note">{note}</p>}
          </div>
          <div className="sl-header-actions">
            {editMode ? (
              <>
                {hiddenIds.size > 0 && (
                  <button className="sl-reset-btn" onClick={resetList}>Reset list</button>
                )}
                <button className="sl-edit-btn sl-edit-btn--active" onClick={() => setEditMode(false)}>
                  Done
                </button>
              </>
            ) : (
              <>
                <button className="sl-top10-btn" onClick={selectTop10} title="Select top 10 by unlock count">
                  Top 10
                </button>
                <button
                  className="sl-edit-btn"
                  onClick={() => setEditMode(true)}
                  aria-label="Edit list"
                  title="Edit list"
                >
                  ✏️
                </button>
              </>
            )}
            <button className="sl-close-btn" onClick={onClose} aria-label="Close">✕</button>
          </div>
        </div>

        {/* ── List ── */}
        <div className={`sl-list${hasSelection ? ' sl-list--has-footer' : ''}`}>
          {visibleItems.length === 0 && (
            <p className="sl-empty">Your bar is fully stocked — nothing to buy!</p>
          )}

          {displayedItems.map(item => {
            const isChecked  = checkedIds.has(item.ingredientId);
            const isExpanded = expandedIds.has(item.ingredientId);
            const hasRecipes = item.recipes.length > 0;

            return (
              <div
                key={item.ingredientId}
                className={`sl-item${isChecked ? ' sl-item--selected' : ''}${editMode ? ' sl-item--edit' : ''}`}
              >
                <div className="sl-item-row">
                  {!editMode && (
                    <button
                      className={`sl-checkbox${isChecked ? ' sl-checkbox--checked' : ''}`}
                      onClick={() => toggleCheck(item.ingredientId)}
                      aria-label={isChecked ? 'Deselect' : 'Select'}
                    >
                      {isChecked && '✓'}
                    </button>
                  )}

                  <div
                    className="sl-item-body"
                    onClick={() => !editMode && hasRecipes && toggleExpand(item.ingredientId)}
                    style={{ cursor: !editMode && hasRecipes ? 'pointer' : 'default' }}
                  >
                    <span className="sl-item-name">{item.name}</span>
                    <div className="sl-item-meta">
                      <span className={`sl-pill sl-pill--${item.category}`}>{item.category}</span>
                      {item.unlocksCount > 0 && (
                        <span className="sl-badge">
                          unlocks {item.unlocksCount} {item.unlocksCount === 1 ? 'recipe' : 'recipes'}
                        </span>
                      )}
                    </div>
                  </div>

                  {editMode ? (
                    <button
                      className="sl-delete-btn"
                      onClick={() => hideItem(item.ingredientId)}
                      aria-label="Remove from list"
                    >
                      ✕
                    </button>
                  ) : hasRecipes ? (
                    <button
                      className={`sl-expand-btn${isExpanded ? ' sl-expand-btn--open' : ''}`}
                      onClick={() => toggleExpand(item.ingredientId)}
                      aria-label={isExpanded ? 'Collapse' : 'Expand'}
                    >
                      ›
                    </button>
                  ) : null}
                </div>

                {!editMode && isExpanded && hasRecipes && (
                  <div className="sl-recipes">
                    {item.recipes.map(name => (
                      <span key={name} className="sl-recipe-chip">{name}</span>
                    ))}
                  </div>
                )}
              </div>
            );
          })}

          {/* Show more / less */}
          {!showAll && remainingCount > 0 && (
            <button className="sl-show-more" onClick={() => setShowAll(true)}>
              Show {remainingCount} more item{remainingCount !== 1 ? 's' : ''}
            </button>
          )}
          {showAll && visibleItems.length > DEFAULT_VISIBLE && (
            <button className="sl-show-more" onClick={() => setShowAll(false)}>
              Show less
            </button>
          )}
        </div>

        {/* ── Sticky export footer (appears when items selected) ── */}
        {hasSelection && (
          <div className="sl-export-footer">
            <span className="sl-export-count">
              {selectedItems.length} item{selectedItems.length !== 1 ? 's' : ''} selected
            </span>
            <div className="sl-export-actions">
              <button className="sl-export-btn" onClick={handleCopy}>
                {copyToast ? '✓ Copied!' : '📋 Copy'}
              </button>
              <button className="sl-export-btn" onClick={handleEmail}>✉️ Email</button>
              <button className="sl-export-btn" onClick={handleSMS}>💬 Text</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
